// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbpvjkbvfidctopscnhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicHZqa2J2ZmlkY3RvcHNjbmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzkwNjEsImV4cCI6MjA1OTExNTA2MX0.Ao5UKHpAEttYukGpVvy_eVor5zT7ykL3VGp4jwdf-EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce'
  }
});